2017-01-13 11:33:52 local_test_v2.py[line:578] INFO start
2017-01-13 11:33:52 local_test_v2.py[line:580] INFO access_20170103122000.log
2017-01-13 11:33:52 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:33:52 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:33:52 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:33:52 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:33:52 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:33:52 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:33:52 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:33:57 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:33:57 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:33:57 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:33:57 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:33:57 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:33:57 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:33:57 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:02 local_test_v2.py[line:510] ERROR log timeout
2017-01-13 11:34:02 local_test_v2.py[line:590] ERROR 
2017-01-13 11:34:02 local_test_v2.py[line:580] INFO access_20170103160500.log
2017-01-13 11:34:02 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:02 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:02 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:02 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:02 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:02 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:34:02 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:07 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:07 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:07 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:07 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:07 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:07 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:34:07 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:12 local_test_v2.py[line:510] ERROR log timeout
2017-01-13 11:34:12 local_test_v2.py[line:590] ERROR 
2017-01-13 11:34:12 local_test_v2.py[line:580] INFO access_20170103164000.log
2017-01-13 11:34:12 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:12 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:12 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:12 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:12 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:12 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:34:12 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:17 local_test_v2.py[line:75] ERROR broker: n21.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:17 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:17 local_test_v2.py[line:75] ERROR broker: n01.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:17 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:17 local_test_v2.py[line:75] ERROR broker: n11.g1.pzt.powzamedia.com:9092 is not available
2017-01-13 11:34:17 local_test_v2.py[line:95] ERROR no broker available
2017-01-13 11:34:17 kafka.py[line:394] INFO Kafka producer closed
2017-01-13 11:34:22 local_test_v2.py[line:510] ERROR log timeout
2017-01-13 11:34:22 local_test_v2.py[line:590] ERROR 
